# Generated by Django 4.2.4 on 2023-08-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('firstName', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('lastName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
