# Generated by Django 4.2.4 on 2023-09-07 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamManagement', '0003_user_has_organization_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255, verbose_name='School Name')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamManagement.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamManagement.team')),
            ],
        ),
    ]
